#!/bin/sh
# This file is managed by Bcfg2. Any local change will be lost.

delay="7200"
current_epoch=$(date +%s)
bcfg2_epoch=$(stat -c "%Y" /etc/bcfg2.info)
diff=$((${current_epoch}-${bcfg2_epoch}))

if [ "$diff" -gt "$delay" ]; then
    echo "BCFG2-CLIENT: No run for more than $delay seconds."
    exit 2
fi

if [ -n "$(grep ^BCFG2_OPTIONS /etc/default/bcfg2 | grep '\-n')" ]; then
    echo "BCFG2-CLIENT: In DRY-RUN mode."
    exit 2
fi

if [ ! -f "/var/log/bcfg2.log" ]; then
    echo "BCFG2-CLIENT: No bcfg2 log file."
    exit 3
fi

if [ -n "$(cat /var/log/bcfg2.log | grep -v Bcfg2.Proxy.SSLHTTPConnection)" ]; then
    echo "BCFG2-CLIENT: Client isn't clean."
    exit 1
fi

echo "BCFG2-CLIENT: Last run was $diff seconds ago."
exit 0
