#!/usr/bin/python3
# Bcfg2 distro probe
# Written by Stephane Graber <stgraber@ubuntu.com>

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

import lsb_release
import sys

try:
    import apt_pkg
except ImportError:
    sys.exit(0)

# Get the information
apt_pkg.init()
info = lsb_release.get_lsb_information()

arch = apt_pkg.config.find("APT::Architecture").lower()
distro = info['ID'].lower()
release = info['RELEASE'].lower()
codename = info['CODENAME'].lower()

# Return the groups
print("group:%s" % arch)
print("group:%s" % distro)
print("group:%s" % codename)
print("group:%s-%s" % (distro, release))

# Return the probe data
print("arch=%s,distro=%s,release=%s,codename=%s" % (arch, distro, release,
                                                    codename))
