#!/bin/sh

# Detect containers vs host
CONTAINER=$(running-in-container)
if [ -n "$CONTAINER" ]; then
    echo "group:container"
    echo "group:$CONTAINER-ve"

    # The next tests are for hosts, so exit now
    exit 0
else
    echo "group:host"
fi

# Export some product information
if [ -d "/sys/class/dmi/id" ]; then
    VENDOR=$(cat /sys/class/dmi/id/chassis_vendor | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9]//g')
    MODEL=$(cat /sys/class/dmi/id/product_name | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9]//g')
fi
echo "group:hw-vendor-${VENDOR:-unknown}"
echo "group:hw-model-${MODEL:-unknown}"

# Hardware monitoring
## HP Advanced Server Management
if [ "$VENDOR" = "hp" ]; then

    # Space delimited list of hpasm excluded systems
    HPEXCLUDELIST="proliantdl165g5p"
    HPEXCLUDED="no"

    for i in $HPEXCLUDELIST; do
        if [ "$i" = "$MODEL" ]; then
            HPEXCLUDED="yes"
        fi
    done

    if [ "$HPEXCLUDED" = "no" ] && \
       echo $MODEL | grep -q "proliant"; then
        echo "group:hpasm"
    fi
fi

## Dell OMSA
if [ "$VENDOR" = "dellinc" ]; then

    # Space delimited list of hpasm excluded systems
    DELLEXCLUDELIST=""
    DELLEXCLUDED="no"

    for i in $DELLEXCLUDELIST; do
        if [ "$i" = "$MODEL" ]; then
            DELLEXCLUDED="yes"
        fi
    done

    if [ "$DELLEXCLUDED" = "no" ] && \
       echo $MODEL | grep -q "poweredge"; then
        echo "group:dellomsa"
    fi
fi

# Detect NIC bonding
if [ -e /sys/class/net/bonding_masters ] && \
   [ "$(cat /sys/class/net/bonding_masters | wc -l)" -gt 0 ]; then
    echo "group:bonding"
fi

# Detect software RAID
if [ -f "/proc/mdstat" ] && grep -q "blocks" /proc/mdstat; then
    echo "group:md-raid"
fi

# Detect HP SmartArray controlers
if [ -d "/sys/module/hpsa" ]; then
    echo "group:hpsa"
fi

exit 0
