#!/usr/bin/python
import subprocess

# Get all IPs
ips = []

# Get IPv4
ip4_cmd = ["ip", "-4", "addr", "show", "scope", "global"]
ip = subprocess.Popen(ip4_cmd, stdout=subprocess.PIPE, universal_newlines=True)
ip.wait()

for line in ip.stdout.read().split("\n"):
    fields = line.split()
    if len(fields) > 2 and fields[0] == "inet":
        ips.append(fields[1].split('/')[0])

# Get IPv6
ip6_cmd = ["ip", "-6", "addr", "show", "scope", "global"]
ip = subprocess.Popen(ip6_cmd, stdout=subprocess.PIPE, universal_newlines=True)
ip.wait()

for line in ip.stdout.read().split("\n"):
    fields = line.split()
    if len(fields) > 2 and fields[0] == "inet6":
        ips.append(fields[1].split('/')[0])

# Sites
sites = {'main': []}
zones = {'mgmt': [],
         'srv':  []}

local_site = "unknown"
local_zone = "unknown"

# Figure out the local site
for site, patterns in sites.items():
    for pattern in patterns:
        for ip in ips:
            if pattern in ip:
                local_site = site
                break
        else:
            continue
        break
    else:
        continue
    break

# Figure out the local zone
for zone, patterns in zones.items():
    for pattern in patterns:
        for ip in ips:
            if pattern in ip:
                local_zone = zone
                break
        else:
            continue
        break
    else:
        continue
    break

# Return the groups
print("group:%s" % local_site)
print("group:%s" % local_zone)

# Return the probe data
print("site=%s,zone=%s" % (local_site, local_zone))
