#!/usr/bin/python3
# Bcfg2 LXC probe
# Written by Stephane Graber <stgraber@ubuntu.com>

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

import json
import os
import sys

try:
    import lxc
except ImportError:
    sys.exit(0)

containers = []

for container_name in sorted(lxc.list_containers()):
    container = lxc.Container(container_name)

    entry = {}
    entry['name'] = container_name
    entry['path'] = container.get_config_item("lxc.rootfs")

    if not os.path.exists(entry['path']):
        continue

    containers.append(entry)

if os.path.exists("/var/lib/lxd/containers/"):
    for container in sorted(os.listdir("/var/lib/lxd/containers")):
        path = os.path.join("/var/lib/lxd/containers/", container)
        if "." in container:
            continue

        entry = {}
        entry['name'] = container
        entry['path'] = "%s/rootfs" % path

        if not os.path.exists(entry['path']):
            continue

        containers.append(entry)

print(json.dumps(containers))
