#!/bin/sh
# Bcfg2 software probe
# Written by Stephane Graber <stgraber@ubuntu.com>

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

FLAGS=""

append_flag() {
    [ -n "$FLAGS" ] && FLAGS=",$1" || FLAGS=$1
}

if [ -x "$(which sshd)" ]; then
    if grep -q AuthorizedKeysCommandUser $(which sshd); then
        append_flag "ssh-supports-authorizedkeyscommand=true"
    else
        append_flag "ssh-supports-authorizedkeyscommand=false"
    fi
fi

if [ -d /run/systemd/system ]; then
    echo "group:systemd"
fi

echo $FLAGS
