#!/usr/bin/python
# This file is managed by Bcfg2. Any local change will be lost.

import socket, pynag

def check_munin_node(options, args):
    if options.host == None:
        raise pynag.ExecutionCritical("Missing host parameter")

    try:
        munin=socket.socket(socket.AF_INET6, socket.SOCK_STREAM)
        munin.connect((options.host,options.port))
        munin.send('list\n')
        munin.send('quit\n')
        data=""
        while 1:
            line=munin.recv(1024)
            if line == "":
                break
            data+=line
        munin.close()
    except:
        raise pynag.ExecutionCritical("Failed to contact munin-node")

    modules=[]
    for line in data.split('\n'):
        if not line.startswith('#'):
            modules=line.split(' ')
            break

    if not 'processes' in modules:
        raise pynag.ExecutionWarning("Modules not loaded")

    return "Running with %s modules loaded" % len(modules)

check_munin_node = pynag.Check(
    func=check_munin_node,
    name="MUNIN-NODE",
    timeout=10
)
check_munin_node.add_option('-H','--host',dest="host",help="Host to check")
check_munin_node.add_option('-P','--port',dest="port",help="Port to check",default=4949,type="int")
check_munin_node.run()
